//! natally — local app shell (Tauri 2), task T0.3 scaffold.
//!
//! This file is deliberately tiny and **frozen for feature tasks**: the
//! `#[tauri::command]` IPC surface is wired through a static, inventory-free
//! command registry so feature tasks never edit `lib.rs` or `main.rs`.
//!
//! # The `natally_plugin!` contract
//!
//! 1. Feature modules live in their own files (e.g. `src/lore/commands.rs`,
//!    owned by their task block) and annotate handlers with
//!    `#[tauri::command]` imported from the `tauri` crate. No custom
//!    procedural macros, no `inventory`, no runtime registration: the handler
//!    table is fully static and resolves at compile time.
//! 2. `src/registry_generated.rs` is the ONLY file that invokes
//!    `natally_plugin!`. It is a generated artifact owned by task I.2, which
//!    regenerates it to (a) declare feature modules at crate root with
//!    `pub mod ...;` and (b) invoke `natally_plugin!` exactly once with the
//!    complete list of command paths (`module::submodule::command_fn`).
//!    Regenerating that one file is how commands join the IPC surface;
//!    `lib.rs` and `main.rs` never change.
//! 3. The committed placeholder registers zero commands —
//!    `tauri::generate_handler![]` with an empty list is valid — so this
//!    scaffold cargo-checks standalone before any feature task runs.
//! 4. `main.rs` calls `natally_lib::run()`, the builder function emitted by
//!    the macro. Shell-level configuration (window set, app-wide plugins once
//!    any are approved by the architecture) lives in `tauri.conf.json` and the
//!    per-platform overlays (`tauri.android.conf.json` — the Android
//!    applicationId is derived from the `identifier`, `mba.robin.natally`,
//!    declared there); feature tasks must not grow `run()`.

/// Static command registry macro for the natally local app. See the
/// `natally_plugin!` contract in the crate documentation above.
///
/// Given a comma-separated list of `#[tauri::command]` fn paths (possibly
/// empty), emits `pub fn run()`: the tauri builder carrying
/// `invoke_handler(tauri::generate_handler![...])` over those paths.
macro_rules! natally_plugin {
    ( $( $cmd:path ),* $(,)? ) => {
        /// Runs the natally local app. Emitted by `natally_plugin!` from the
        /// generated registry (`src/registry_generated.rs`); never edited by hand.
        pub fn run() {
            tauri::Builder::default()
                .invoke_handler(tauri::generate_handler![ $( $cmd ),* ])
                .run(tauri::generate_context!())
                .expect("natally: fatal error while running the tauri application");
        }
    };
}

// Stable include hook — generated registry, regenerated by task I.2.
// See the `natally_plugin!` contract above; this line never changes.
include!("registry_generated.rs");
