// natally design tokens — GENERATED by packages/design-tokens/scripts/gen.mjs from
// LIBS/UI/FIGMA/TOKENS.md (frozen Figma complement) + STATE-LEDGER.json variable ids.
// Do not edit by hand — rerun: node packages/design-tokens/scripts/gen.mjs

export const COLOUR = {
  midnight: "#120C1C",
  "midnight-2": "#1C1428",
  "midnight-3": "#271C36",
  hairline: "#322641",
  vellum: "#F1E8D8",
  "vellum-muted": "#A99DAE",
  gilt: "#D4AF37",
  orbglow: "#F2A38C",
  moonlight: "#9FB4FF",
  ember: "#E2604F",
} as const;

export const ZODIAC = {
  aries: "#D68585",
  taurus: "#D6AD85",
  gemini: "#D6D685",
  cancer: "#ADD685",
  leo: "#85D685",
  virgo: "#85D6AD",
  libra: "#85D6D6",
  scorpio: "#85ADD6",
  sagittarius: "#8585D6",
  capricorn: "#AD85D6",
  aquarius: "#D685D6",
  pisces: "#D685AD",
} as const;

export const RADIUS = {
  plate: "12px",
  button: "10px",
  chip: "8px",
  pill: "999px",
} as const;

export const SPACING = {
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "6": "24px",
  "8": "32px",
} as const;

export const STROKE = {
  hairline: "1px",
} as const;

export const SIZE = {
  touch: "44px",
  stage: "200px",
  avatar: "44px",
} as const;

export const COLOUR_VAR = {
  midnight: "--color-midnight",
  "midnight-2": "--color-midnight-2",
  "midnight-3": "--color-midnight-3",
  hairline: "--color-hairline",
  vellum: "--color-vellum",
  "vellum-muted": "--color-vellum-muted",
  gilt: "--color-gilt",
  orbglow: "--color-orbglow",
  moonlight: "--color-moonlight",
  ember: "--color-ember",
} as const;

export const ZODIAC_VAR = {
  aries: "--color-z-aries",
  taurus: "--color-z-taurus",
  gemini: "--color-z-gemini",
  cancer: "--color-z-cancer",
  leo: "--color-z-leo",
  virgo: "--color-z-virgo",
  libra: "--color-z-libra",
  scorpio: "--color-z-scorpio",
  sagittarius: "--color-z-sagittarius",
  capricorn: "--color-z-capricorn",
  aquarius: "--color-z-aquarius",
  pisces: "--color-z-pisces",
} as const;

export const RADIUS_VAR = {
  plate: "--radius-plate",
  button: "--radius-button",
  chip: "--radius-chip",
  pill: "--radius-pill",
} as const;

export const SPACING_VAR = {
  "1": "--spacing-1",
  "2": "--spacing-2",
  "3": "--spacing-3",
  "4": "--spacing-4",
  "6": "--spacing-6",
  "8": "--spacing-8",
} as const;

export const STROKE_VAR = {
  hairline: "--stroke-hairline",
} as const;

export const SIZE_VAR = {
  touch: "--size-touch",
  stage: "--size-stage",
  avatar: "--size-avatar",
} as const;

export const VARIABLE_ID = {
  "--color-midnight": "VariableID:2:3",
  "--color-midnight-2": "VariableID:2:4",
  "--color-midnight-3": "VariableID:2:5",
  "--color-hairline": "VariableID:2:6",
  "--color-vellum": "VariableID:2:7",
  "--color-vellum-muted": "VariableID:2:8",
  "--color-gilt": "VariableID:2:9",
  "--color-orbglow": "VariableID:2:10",
  "--color-moonlight": "VariableID:2:11",
  "--color-ember": "VariableID:2:12",
  "--color-z-aries": "VariableID:2:13",
  "--color-z-taurus": "VariableID:2:14",
  "--color-z-gemini": "VariableID:2:15",
  "--color-z-cancer": "VariableID:2:16",
  "--color-z-leo": "VariableID:2:17",
  "--color-z-virgo": "VariableID:2:18",
  "--color-z-libra": "VariableID:2:19",
  "--color-z-scorpio": "VariableID:2:20",
  "--color-z-sagittarius": "VariableID:2:21",
  "--color-z-capricorn": "VariableID:2:22",
  "--color-z-aquarius": "VariableID:2:23",
  "--color-z-pisces": "VariableID:2:24",
  "--radius-plate": "VariableID:2:25",
  "--radius-button": "VariableID:2:26",
  "--radius-chip": "VariableID:2:27",
  "--radius-pill": "VariableID:2:28",
  "--spacing-1": "VariableID:2:29",
  "--spacing-2": "VariableID:2:30",
  "--spacing-3": "VariableID:2:31",
  "--spacing-4": "VariableID:2:32",
  "--spacing-6": "VariableID:2:33",
  "--spacing-8": "VariableID:2:34",
  "--stroke-hairline": "VariableID:2:35",
  "--size-touch": "VariableID:2:36",
  "--size-stage": "VariableID:2:37",
  "--size-avatar": "VariableID:2:38",
} as const;

export const TOKEN_COUNT = 36;
