// GENERATED by scripts/gen-routes.mjs (I.1) — do not edit; regenerate instead.
import { registerRoute } from "./router.js";

registerRoute({ path: "/", load: () => import("../screens/conversation/route.js") });
