// generated by gen-routes.mjs — do not edit
//
// natally — I.1 route registry consolidation. Side-effect imports of every
// module under src/screens/** holding a registerRoute call site (frozen
// route set, src/ui/router.ts): importing the module is what registers its
// route(s). Regenerate with `node apps/local/scripts/gen-routes.mjs` —
// re-running reproduces this file byte-for-byte. Imports are ordered
// path-sorted by the first route each module registers.
//
// Implemented screens registered nowhere (no route, by design — the wiring
// layer mounts these directly, per each module's own header):
//   screens/first-light
//   screens/glossary
//   screens/plate-natal
//   screens/splash

import "../screens/conversation/index"; // registers "/"
import "../screens/about/index"; // registers "/about"
import "../screens/atlas/index"; // registers "/atlas/:plate"
import "../screens/checkout/index"; // registers "/checkout"
import "../screens/paywall/index"; // registers "/paywall"
import "../screens/people/index"; // registers "/people", "/people/:id"
import "../screens/settings/index"; // registers "/settings"

import { ROUTE_PATHS, type RouteRegistry, routeRegistry } from "./router";

/**
 * Entry point for router consumers. The side-effect imports above have
 * already registered every frozen route by the time this module loads;
 * this returns the populated registry after asserting it is complete. A
 * missing path means the generated file is stale against the screens —
 * regenerate it, never improvise routes.
 */
export function registerAllRoutes(): RouteRegistry {
  const registry = routeRegistry();
  const missing = ROUTE_PATHS.filter((path) => !registry.has(path));
  if (missing.length > 0) {
    throw new Error(
      `registerAllRoutes: route(s) not registered [${missing.join(", ")}] — regenerate routes.generated.ts (node apps/local/scripts/gen-routes.mjs)`,
    );
  }
  return registry;
}
