//! License tokens (§9.3): Ed25519-signed compact JSON
//! `base64url({"alg":"EdDSA"}).base64url(payload).base64url(signature)`, payload exactly
//! `LicenseTokenPayloadSchema` from packages/billing/src/types.ts:
//! `{ sub, tier: 'unlimited', iat, exp: null, iss: 'natally-license-bridge', jti }`.

use crate::crypto;
use crate::state::Bridge;
use axum::extract::State;
use axum::Json;
use serde::Deserialize;
use serde::Serialize;
use serde_json::json;

pub const LICENSE_ISSUER: &str = "natally-license-bridge";

#[derive(Serialize)]
pub struct LicenseTokenPayload {
    pub sub: String,
    pub tier: String, // always "unlimited" (z.literal in the shared schema)
    pub iat: i64,
    pub exp: Option<i64>, // serialized as null
    pub iss: String,
    pub jti: String,
}

pub struct VerificationFailure {
    pub reason: &'static str,
}

/// Mint a token for `sub`; `jti` is freshly generated by the caller and recorded so a
/// refund can revoke exactly this token.
pub fn mint(bridge: &Bridge, sub: &str) -> (String, String) {
    let jti = crypto::random_hex(16);
    let payload = LicenseTokenPayload {
        sub: sub.to_string(),
        tier: "unlimited".to_string(),
        iat: crypto::unix_now(),
        exp: None,
        iss: LICENSE_ISSUER.to_string(),
        jti: jti.clone(),
    };
    (sign_payload(bridge, &payload), jti)
}

pub fn sign_payload(bridge: &Bridge, payload: &LicenseTokenPayload) -> String {
    use ed25519_dalek::Signer;
    let header = crypto::b64url_encode(br#"{"alg":"EdDSA"}"#);
    let payload_json = serde_json::to_string(payload).expect("payload serialize");
    let payload_seg = crypto::b64url_encode(payload_json.as_bytes());
    let message = format!("{header}.{payload_seg}");
    let signature = bridge.signing.sign(message.as_bytes());
    format!("{message}.{}", crypto::b64url_encode(&signature.to_bytes()))
}

/// Offline verification: transport parse, Ed25519 check, strict claim checks
/// (tier literal, iss literal, exp null), then deny-list membership.
pub fn verify(bridge: &Bridge, token: &str) -> Result<serde_json::Value, VerificationFailure> {
    let parts: Vec<&str> = token.split('.').collect();
    if parts.len() != 3 {
        return Err(VerificationFailure { reason: "malformed" });
    }
    let (header_seg, payload_seg, signature_seg) = (parts[0], parts[1], parts[2]);
    let header = crypto::b64url_decode(header_seg)
        .and_then(|b| serde_json::from_slice::<serde_json::Value>(&b).ok());
    match header {
        Some(v) if v == json!({"alg": "EdDSA"}) => {}
        _ => return Err(VerificationFailure { reason: "malformed" }),
    }
    let payload_bytes = crypto::b64url_decode(payload_seg)
        .ok_or(VerificationFailure { reason: "malformed" })?;
    let signature = crypto::b64url_decode(signature_seg)
        .ok_or(VerificationFailure { reason: "malformed" })?;
    if signature.len() != 64 {
        return Err(VerificationFailure { reason: "malformed" });
    }
    use ed25519_dalek::{Signature, Verifier, VerifyingKey};
    let verifying = VerifyingKey::from_bytes(&bridge.signing.verifying_key().to_bytes())
        .expect("verifying key");
    let signature = Signature::from_slice(&signature).expect("64-byte signature");
    let message = format!("{header_seg}.{payload_seg}");
    verifying
        .verify(message.as_bytes(), &signature)
        .map_err(|_| VerificationFailure { reason: "signature" })?;

    let payload: serde_json::Value = serde_json::from_slice(&payload_bytes)
        .map_err(|_| VerificationFailure { reason: "malformed" })?;
    // Strict claim checks mirroring LicenseTokenPayloadSchema (strictObject semantics:
    // unknown fields make the payload one the client would reject, so treat as invalid).
    let known_keys = ["sub", "tier", "iat", "exp", "iss", "jti"];
    let no_extras = payload.as_object().is_some_and(|o| {
        o.keys().all(|k| known_keys.contains(&k.as_str())) && o.len() == known_keys.len()
    });
    let sub = payload.get("sub").and_then(|v| v.as_str()).unwrap_or("");
    let jti = payload.get("jti").and_then(|v| v.as_str()).unwrap_or("");
    let tier_ok = payload.get("tier").and_then(|v| v.as_str()) == Some("unlimited");
    let iss_ok = payload.get("iss").and_then(|v| v.as_str()) == Some(LICENSE_ISSUER);
    let exp_ok = payload.get("exp") == Some(&serde_json::Value::Null);
    let iat_ok = payload.get("iat").and_then(|v| v.as_i64()).is_some();
    if !no_extras || sub.is_empty() || jti.is_empty() || !tier_ok || !iss_ok || !exp_ok || !iat_ok {
        return Err(VerificationFailure { reason: "claims" });
    }

    if is_revoked(bridge, jti) {
        return Err(VerificationFailure { reason: "revoked" });
    }
    Ok(payload)
}

pub fn is_revoked(bridge: &Bridge, jti: &str) -> bool {
    let db = bridge.db.lock().expect("db lock");
    db.query_row(
        "SELECT 1 FROM revocations WHERE jti = ?1",
        [jti],
        |_| Ok(()),
    )
    .is_ok()
}

// ---------- HTTP surface ----------

#[derive(Deserialize)]
pub struct VerifyRequest {
    pub token: String,
}

pub async fn verify_handler(
    State(bridge): State<std::sync::Arc<Bridge>>,
    Json(req): Json<VerifyRequest>,
) -> Json<serde_json::Value> {
    match verify(&bridge, &req.token) {
        Ok(payload) => Json(json!({ "valid": true, "payload": payload })),
        Err(VerificationFailure { reason }) => Json(json!({ "valid": false, "reason": reason })),
    }
}
