use std::{env, error::Error, fmt::Write, fs, path::PathBuf};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").ok_or("missing manifest dir")?);
    let plugins_dir = manifest_dir.join("src/plugins");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").ok_or("missing Cargo output dir")?);

    // Watch the parent as well so adding the first plugin triggers regeneration.
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=permissions");
    println!("cargo:rerun-if-changed=icons");

    let mut plugins = Vec::new();
    if plugins_dir.is_dir() {
        for entry in fs::read_dir(&plugins_dir)? {
            let entry = entry?;
            let path = entry.path();
            let entrypoint = if path.is_file() && path.extension().is_some_and(|ext| ext == "rs") {
                path.clone()
            } else if path.is_dir() && path.join("mod.rs").is_file() {
                path.join("mod.rs")
            } else {
                continue;
            };
            let name = if path.is_dir() {
                path.file_name()
            } else {
                path.file_stem()
            }
            .and_then(|name| name.to_str())
            .ok_or("plugin name must be UTF-8")?
            .to_owned();

            if !name.starts_with(|c: char| c.is_ascii_lowercase())
                || !name
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
                || matches!(name.as_str(), "mod" | "self" | "super" | "crate")
            {
                return Err(format!("invalid plugin module name: {name}").into());
            }
            plugins.push((name, entrypoint));
        }
    }
    plugins.sort_by(|a, b| a.0.cmp(&b.0));
    for pair in plugins.windows(2) {
        if pair[0].0 == pair[1].0 {
            return Err(format!("duplicate plugin module: {}", pair[0].0).into());
        }
    }

    let mut registry = String::from("// Generated by build.rs from src/plugins; do not edit.\n");
    let mut attributes = tauri_build::Attributes::new();
    for (name, entrypoint) in &plugins {
        // Paths derive from the checkout on this host; none are committed or hardcoded.
        writeln!(registry, "#[path = {:?}]\nmod r#{name};", entrypoint)?;
        // Each feature owns permissions/<name> and its own capabilities/*.json file.
        let plugin_name: &'static str = Box::leak(name.clone().into_boxed_str());
        attributes = attributes.plugin(plugin_name, tauri_build::InlinedPlugin::new());
    }
    registry.push_str("pub(crate) fn register<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {\n    builder\n");
    for (name, _) in &plugins {
        writeln!(registry, "        .plugin(r#{name}::init::<R>())")?;
    }
    registry.push_str("}\n");
    fs::write(out_dir.join("natally_plugin_registry.rs"), registry)?;

    tauri_build::try_build(attributes)?;
    Ok(())
}
