#!/usr/bin/env python3
"""Publish a navigable index of the frozen Figma exports without altering artwork."""
from html import escape
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
FIGMA = ROOT / "LIBS/UI/FIGMA"
LEDGER = json.loads((FIGMA / "STATE-LEDGER.json").read_text())
ORDER = ["conversation", "first-light", "splash", "plate-natal", "atlas-natal",
         "atlas-synastry", "atlas-today", "people", "settings", "about",
         "glossary-callout", "paywall", "checkout"]
DEFAULTS = {"conversation": "Idle", "first-light": "name", "splash": "loading",
            "plate-natal": "withHouses", "glossary-callout": "overAtlas",
            "paywall": "trial-active", "checkout": "handoff"}
ALIASES = {("people", "rail"): "desktopRail",
           ("settings", "license"): "license-section-mobile",
           ("settings", "web-license"): "license-section-web"}


def normalized(value):
    return re.sub(r"[^a-z0-9]", "", value.lower())


def figma_link(node_id):
    return LEDGER["fileUrl"] + "?node-id=" + node_id.replace(":", "-")


sections, navigation, markdown = [], [], [
    "# natally — frozen Figma design index\n",
    "Generated by `scripts/generate-design-gallery.py` from `LIBS/UI/FIGMA/STATE-LEDGER.json` "
    "and the unchanged PNG exports beside each `SCREEN.md`.\n",
    "[Open the visual gallery](DESIGN-GALLERY.html) · "
    f"[Recorded Figma file]({LEDGER['fileUrl']})\n",
    "The baseline was frozen on 2026-09-03 and amended on 2026-09-04. "
    "D19 records that the September 4 approval governs implementation. "
    "On 2026-09-13 the Figma connector returned only an empty Cover page for the recorded file. "
    "The frame links below are preserved provenance, not a claim that the live frames remain accessible.\n",
]
frame_count = image_count = 0
for slug in ORDER:
    key = "screen-" + slug
    folder = FIGMA / "screens" / key
    variants = {k: v for k, v in LEDGER["screens"][key].items() if isinstance(v, str)}
    images = {}
    for image_path in sorted(folder.glob("screenshot*.png")):
        suffix = image_path.stem.removeprefix("screenshot").lstrip("-")
        variant = ALIASES.get((slug, suffix), suffix or DEFAULTS.get(slug, "mobile"))
        matched = next((name for name in variants if normalized(name) == normalized(variant)), None)
        if matched is None:
            raise ValueError(f"Unmapped frozen export: {image_path}")
        images[matched] = image_path
    label = slug.replace("-", " ").capitalize()
    navigation.append(f'<a href="#{slug}">{escape(label)}</a>')
    page_url = figma_link(LEDGER["pages"][key])
    markdown += [f"\n## {label}\n", f"[Figma page]({page_url}) · "
                 f"[Screen specification](../LIBS/UI/FIGMA/screens/{key}/SCREEN.md)\n",
                 "| Variant | Recorded Figma frame | Frozen image |", "|---|---|---|"]
    cards = []
    for variant, node_id in variants.items():
        frame_count += 1
        url = figma_link(node_id)
        img = images.get(variant)
        title = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", variant).replace("-", " ")
        if img:
            image_count += 1
            src = "../" + img.relative_to(ROOT).as_posix()
            visual = (f'<a class="image" href="{escape(src)}" target="_blank" '
                      f'aria-label="Open full-size {escape(label)} — {escape(title)}">'
                      f'<img src="{escape(src)}" alt="{escape(label)} — {escape(title)}, '
                      'original frozen Figma export" loading="lazy"></a>')
            saved = f"[View original]({src})"
            status = "Original export"
        else:
            visual = '<div class="missing">No PNG export was saved for this variant.</div>'
            saved = "No saved PNG"
            status = "Recorded frame only"
        cards.append(f'<article><div class="card-heading"><h3>{escape(title)}</h3>'
                     f'<span>{status}</span></div>{visual}<a class="frame-link" href="{escape(url)}" '
                     f'target="_blank" rel="noopener">Figma frame {escape(node_id)} ↗</a></article>')
        markdown.append(f"| {variant} | [{node_id}]({url}) | {saved} |")
    sections.append(f'<section id="{slug}" data-search="{escape((label + " " + " ".join(variants)).lower())}">'
                    f'<div class="section-heading"><h2>{escape(label)}</h2>'
                    f'<a href="{escape(page_url)}" target="_blank" rel="noopener">Recorded Figma page ↗</a></div>'
                    f'<div class="cards">{"".join(cards)}</div></section>')

summary = f"{len(ORDER)} screen groups · {frame_count} recorded frames · {image_count} original image exports"
html = '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>natally — frozen Figma screens</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f1ec;color:#26222c;font:15px/1.55 system-ui,sans-serif}
a{color:#564487;text-underline-offset:3px}header{padding:40px 40px 28px;border-bottom:1px solid #d7d2dc;background:#fffdfa}
.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#6b6472}h1{font-size:36px;line-height:1.2;margin:12px 0}
header p{max-width:880px;margin:12px 0;color:#5b5463}.source{display:inline-block;padding:10px 16px;background:#30223f;color:#fff;border-radius:8px;text-decoration:none}
.layout{display:grid;grid-template-columns:215px minmax(0,1fr)}nav{position:sticky;top:0;height:100vh;overflow:auto;padding:26px 20px;border-right:1px solid #d7d2dc}
nav a{display:block;padding:7px 8px;text-decoration:none;border-radius:4px}nav a:hover{background:#e7e1ef}
main{padding:24px 32px;min-width:0}label{display:block;font-weight:600}input{margin:8px 0 22px;padding:12px;border:1px solid #b7afc1;border-radius:6px;width:min(100%,480px);font:inherit;background:white}
section{scroll-margin-top:20px;margin-bottom:50px}section[hidden]{display:none}.section-heading{display:flex;flex-wrap:wrap;align-items:center;gap:10px;justify-content:space-between;margin-bottom:16px}
h2{font-size:25px;margin:0}h3{font-size:15px;margin:0}.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:18px;align-items:start}
article{background:#fff;border:1px solid #d7d2dc;border-radius:10px;overflow:hidden}.card-heading{padding:14px 16px}.card-heading span{display:block;font-size:12px;color:#766d80;margin-top:3px}
.image{height:350px;display:flex;align-items:flex-start;justify-content:center;background:#e9e5ed;padding:12px}.image img{max-height:100%;max-width:100%;object-fit:contain;object-position:top;box-shadow:0 2px 12px #21192a22}
.frame-link{display:block;padding:12px 16px;font-size:13px}.missing{padding:40px 20px;color:#736a7c;background:#f3f0f5;min-height:140px;display:grid;place-items:center;text-align:center}
.notice{border-left:3px solid #a27d30;padding-left:14px}footer{padding:20px 32px;border-top:1px solid #d7d2dc;color:#746c7c;font-size:13px}
@media(max-width:700px){header{padding:24px}h1{font-size:28px}.layout{display:block}nav{position:static;height:auto;border-right:0;border-bottom:1px solid #d7d2dc;display:flex;overflow-x:auto;padding:12px;gap:4px}nav a{white-space:nowrap}main{padding:20px}.cards{grid-template-columns:repeat(auto-fill,minmax(230px,1fr))}}
</style></head><body>
<header><div class="eyebrow">Design reference · original exports</div><h1>natally — frozen Figma screens</h1>
<p>SUMMARY</p><a class="source" href="FILE_URL" target="_blank" rel="noopener">Open recorded Figma file ↗</a>
<p>Frozen September 3, 2026; amended September 4. D19 records that the September 4 approval governs implementation. Click any image to inspect the original at full size.</p>
<p class="notice">The Figma connector returned only an empty Cover page on September 13. These unchanged local exports remain available. Links preserve the recorded frame IDs; variants without a saved PNG are labelled below.</p>
</header><div class="layout"><nav aria-label="Screen groups">NAVIGATION</nav><main>
<label for="search">Find a screen or variant</label><input id="search" type="search" placeholder="Conversation, settings, checkout…">
SECTIONS
</main></div><footer>Generated from LIBS/UI/FIGMA/STATE-LEDGER.json and screens/*/screenshot*.png by scripts/generate-design-gallery.py. No screen artwork has been recreated.</footer>
<script>document.querySelector('#search').addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();for(const section of document.querySelectorAll('section[data-search]'))section.hidden=!section.dataset.search.includes(query)});</script>
</body></html>'''
html = html.replace("SUMMARY", summary).replace("FILE_URL", escape(LEDGER["fileUrl"]))
html = html.replace("NAVIGATION", "".join(navigation)).replace("SECTIONS", "\n".join(sections))
(ROOT / "DOCS/DESIGN-GALLERY.html").write_text(html)
(ROOT / "DOCS/DESIGN-INDEX.md").write_text("\n".join(markdown) + "\n")
print(summary)
print("DOCS/DESIGN-GALLERY.html and DOCS/DESIGN-INDEX.md written")
