#!/usr/bin/env node
// I.1 — route registry generator. Scans src/screens/**/route.tsx and emits
// routes.generated.ts: one registerRoute call per screen, mapped through the
// ROUTE_MAP below (closed 8-route vocabulary, router.ts). Re-running regenerates
// identically; the output is committed. A screen without a ROUTE_MAP entry fails
// generation loudly (SC1: closed set, no silent appends).
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const screensRoot = join(appRoot, "src", "screens");

/** Screen directory → route path (router.ts ROUTE_PATHS is the closed vocabulary). */
const ROUTE_MAP = {
  conversation: "/",
  // W3 fills these as the screens land from the Stitch v2 source:
  // "plate-natal": null, atlas: "/atlas/:plate", people: "/people",
  // settings: "/settings", paywall: "/paywall", checkout: "/checkout", about: "/about",
};

const screens = readdirSync(screensRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const lines = [
  "// GENERATED by scripts/gen-routes.mjs (I.1) — do not edit; regenerate instead.",
  'import { registerRoute } from "./router.js";',
];
let count = 0;
for (const screen of screens) {
  const routeFile = join(screensRoot, screen, "route.tsx");
  if (!existsSync(routeFile)) continue;
  const path = ROUTE_MAP[screen];
  if (!path) {
    console.error(`gen-routes: screen "${screen}" has route.tsx but no ROUTE_MAP entry`);
    process.exit(1);
  }
  lines.push(
    `registerRoute({ path: ${JSON.stringify(path)}, load: () => import("../screens/${screen}/route.js") });`,
  );
  count += 1;
}
lines.push("");
writeFileSync(join(appRoot, "src", "ui", "routes.generated.ts"), lines.join("\n"));
console.log(`gen-routes: ${count} route(s) registered -> src/ui/routes.generated.ts`);
